node {
	//def gradleHome = '/var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/gradle6.8.2'	
	//def path = tool name: 'GRADLE6_HOME', type: 'gradle'		
	   stage('00 clean ws') {		 //  cleanWs()
		   cleanWs disableDeferredWipeout: true, deleteDirs: true
	   }

	stage("01 github checkout"){
		git 'https://github.com/xt4k/pipeExamples2'		
	}
	
	stage('03 show me more') {
		sh "ls"		
	}
	
	stage('05 Run_Auto-Test (in_Gradle)') {			
				sh './gradlew -Denv=remote2 clean test'					
	}	

	stage("03 allure report add") {
		allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
	}	
}
