node {
	def gradleHome = '/var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/gradle7'
	   stage('00 clean ws') {
		   cleanWs()
	   }

	stage("01 github checkout"){
		git 'https://github.com/xt4k/pipeExamples2'
	}
	//stage('02 Run_Auto-Test (in_Gradle)') {	
		 withGradle {
		// sh "'${gradleHome}/bin/gradle' clean compileJava test"
		//sh "'${gradleHome}/bin/gradle' --info -Denv=remote2 clean test"
		//sh "./gradlew --info -Denv=remote2 clean test"
		sh "'${BUILD_URL}'/bin/gradle --info -Denv=remote2 clean test"
		 }
	//}	

	stage("03 allure report add") {
		allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
	}	
}
