node {
	   stage('00 clean ws') {
		   cleanWs()
	   }

	stage("01 github checkout"){
		git 'https://github.com/xt4k/pipeExamples2'
		}
	stage('02 Run_Auto-Test (in_Gradle)') {
		withGradle () {
			sh 'gradle clean -Denv=remote2 test'
		}
	}
	stage("03 allure report add") {
                allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
                }	
}
